### ISSUE TITLE
Feature: Save filename as emoji name

### ISSUE THREAD

**Issue by four43** [labynocle/slack_emoji_downloader#1]
To make this the most usable and portable it would be nice to have the filename match the name used in slack. For example:

`:hello-world:` would reference the file `hello-world.png`

**Comment by Tibshot** [comment]
Hi, 

Filenames seem to be already based from slack emoji names... hello-world.png is already corresponding to Slack :hello-world: emoji.

Thanks,

**Comment by labynocle** [comment]
hi @four43 :wave: 

Thank you for opening the first issue :rocket: ^^

As @Tibshot said, the name is supposed to be the same! Do you have an example where it doesn't work? :eyes:

**Comment by four43** [comment]
I'm sorry. My coworkers are just bad at naming some of these `aaaaaaa.png` is a real emoji. Go figure.

Hey thanks for the great project! This is fun.
